### PR TITLE
Added RBD (rapid belt device)

### PR DESCRIPTION
**Pull request by JohnTheAutist**
## About The Pull Request

Added rapid belt device (RBD). 
Effectively an RPD but for belts. You can create belts in 4 directions and a switch. They'll all be linked based on the ID you set.
Added it to cargo techs backpack, auolathe and order console. Also set belt price to 0 since the RBD functions like a pipe dispenser. It still requires iron to be in the lathe but does not charge you iron.

## Why It's Good For The Game

Gives belts a chance to be more autistic.

## Changelog
:cl: sneed
add: Rapid belt device
add: RBD to autolathe
add: RBD to cargo tech backpack
add: RBD to order console
balance: Belt mat price is now 0
/:cl:

### CODE REVIEW

**Comment by sperky7933** [comment]
polling. i like this a lot and i think this is epic

**Comment by JohnTheAutist** [comment]
> polling. i like this a lot and i think this is epic

I think it's the first step to building out belt autism. More belts like diagonal ones or filter. Maybe cargo centric ones like being able to read who ordered the crate and then doing something based on that. Would be helpful if we ever got that waste pipe delivery system /tg/ added where there's a waste pipe that goes to each departments airlock for fast deliveries.

**Comment by sperky7933** [comment]
>Would be helpful if we ever got that waste pipe delivery system /tg/ added where there's a waste pipe that goes to each departments airlock for fast deliveries.

already a thing, it's called disposals

**Comment by JohnTheAutist** [comment]
> > Would be helpful if we ever got that waste pipe delivery system /tg/ added where there's a waste pipe that goes to each departments airlock for fast deliveries.
>
> already a thing, it's called disposals

dept deliveries

It's disposals but backwards. Instead of stuff going to cargo it lets cargo send stuff to other departments. Specifically for mail and boxes.

**Comment by sperky7933** [comment]
> It's disposals but backwards. Instead of stuff going to cargo it lets cargo send stuff to other departments. Specifically for mail and boxes.

yeah. if you package something in package paper and put a destination, you can send stuff

**Comment by JohnTheAutist** [comment]
> > It's disposals but backwards. Instead of stuff going to cargo it lets cargo send stuff to other departments. Specifically for mail and boxes.
> 
> yeah. if you package something in package paper and put a destination, you can send stuff

Oh damn that's cool. If I ever get around to automated belts/machines for cargo I'll make a machine that can wrap things and another that can stamp a location. Also things with mulebot like beacons and docking stations tied to machines so they can act like automated drones.

**Comment by sperky7933** [comment]
few bugs i notice:
1. id is set to 255 initially when spawned in, but can only be adjusted from 0-200. i believe the id should be able to be set to 255, i could be wrong
2. placement direction icons arent done. literally i dont care if you use the same direction icons as with pipes, just make them point in the direction they move by using a preset icon like an arrow or a volume pump icon
3. "conveyor belt layer" should be renamed to "lever" or something
4. remove the "wrench" option as toggling it off does nothing, or you can make it work
5. put a period at the end of the description

**Comment by JohnTheAutist** [comment]
>     2. placement direction icons arent done. literally i dont care if you use the same direction icons as with pipes, just make them point in the direction they move by using a preset icon like an arrow or a volume pump icon
> 

How did you fix the icons in the RPD UI for vmstation? I wasn't able to figure out how to get them to show. Otherwise I would have tested the icons

> "conveyor belt layer" should be renamed to "lever" or something

>
Confused about this. It says lever for me.

RBD

**Comment by sperky7933** [comment]
> > ```
> > 2. placement direction icons arent done. literally i dont care if you use the same direction icons as with pipes, just make them point in the direction they move by using a preset icon like an arrow or a volume pump icon
> > ```
> 
> How did you fix the icons in the RPD UI for vmstation? I wasn't able to figure out how to get them to show. Otherwise I would have tested the icons
> 
> > "conveyor belt layer" should be renamed to "lever" or something
> 
> > 
> 
> Confused about this. It says lever for me.

fuck i've gotten the exact same bug when hosting the server itself. i do not know how i fixed it, it happened coincidentally when installing random ass libraries to my server in a last ditch attempt to get rust_g to work. if you're on windows, honestly, tough luck because i can't help you there
also it says in your screenshot "conveyor belt layer" while all it does is spawn a lever, so just rename "conveyor belt layer" to "lever"

**Comment by JohnTheAutist** [comment]
> fuck i've gotten the exact same bug when hosting the server itself. i do not know how i fixed it, it happened coincidentally when installing random ass libraries to my server in a last ditch attempt to get rust_g to work. if you're on windows, honestly, tough luck because i can't help you there

I'm hosting on Linux

> also it says in your screenshot "conveyor belt layer" while all it does is spawn a lever, so just rename "conveyor belt layer" to "lever"
>

What? It says lever. Even in the code it says lever. I'm just going to change it to switch.
` 		new /datum/pipe_info/belt_switch("Conveyor Belt Lever",		/obj/item/conveyor_switch_construct)`
https://github.com/not-a-furry/vmstation/pull/60/files#diff-05564cd8c756643bb9395832fdedbc6cfc6101e1e8ef85fb6bf3097bc8810091R80

**Comment by JohnTheAutist** [comment]
I fixed the UI. Basically it just says north/south/east/west for the RBD. This is probably the best solution anyways because the sprites aren't very clear which direction the belt faces.

**Comment by JohnTheAutist** [comment]
@not-a-furry  I fixed the UI and all the other issues. Basically it just says north/south/east/west for the RBD. This is probably the best solution anyways because the sprites aren't very clear which direction the belt faces.

**Comment by sperky7933** [comment]
> @not-a-furry I fixed the UI and all the other issues. Basically it just says north/south/east/west for the RBD. This is probably the best solution anyways because the sprites aren't very clear which direction the belt faces.

epic, good shit. how did you fix it?

**Comment by JohnTheAutist** [comment]
> > @not-a-furry I fixed the UI and all the other issues. Basically it just says north/south/east/west for the RBD. This is probably the best solution anyways because the sprites aren't very clear which direction the belt faces.
> 
> epic, good shit. how did you fix it?

https://github.com/not-a-furry/vmstation/pull/60/files#diff-f89d41bfd1da3c05a18d35b5684d760ec9340b35488de74291133f8c37b5f98eR2
I couldn't get the RPD UI sprites working so I made the RBD just use text. Basically went into the UI code and set it so that if it's the RBD then instead of displaying icons for directions it prints text saying the direction. It's kinda ugly but I think this is the best way unless belts were re-sprited to show what direction they're facing better.

**Comment by sperky7933** [comment]
last issue
the dispenser doesn't destroy belts when on destroy mode - interrupted by the syncing of ID
both build mode and destroy mode can be toggled on the same time

**Comment by sperky7933** [comment]
actually build mode and destroy mode can be on at the same time, as long as it skips the sync and just destroys when clicked on a belt/lever. you know what im saying? just get it to destroy and its good

**Comment by JohnTheAutist** [comment]
> actually build mode and destroy mode can be on at the same time, as long as it skips the sync and just destroys when clicked on a belt/lever. you know what im saying? just get it to destroy and its good

> last issue the dispenser doesn't destroy belts when on destroy mode - interrupted by the syncing of ID both build mode and destroy mode can be toggled on the same time

It works like the RPD. It only destroys deconstructed (item) belts. I.E. if you use your crowbar on them and turn them into an item it'll destroy them just like how using a wrench on pipes allows the RPD to destroy them.

**Comment by sperky7933** [comment]
shit my bad

**Pull request merged**
