### PR TITLE
Adds a tool storage, adds trash into trash bins, adds bookcases in dorms.

### PR DESCRIPTION
**Pull request by hamurlik**
## About The Pull Request

Shrunk maint recycle area, made tool storage from it. Added random trash or grille loot spawner into bins. Added a few random bookcases into dorms.
## Why It's Good For The Game
Every station has a tool storage, no reason why ministation shouldn't have one.

Tool storage is necessary for tiders. Trash in bins for immersion, and something for janitors to do. Books are great, an ic information dump, would be bad if ministation left out of it.
## Changelog
:cl:
tweak: shrunk maint recycle area
add: tool storage from above mentioned maint recycle area
add: tool storage assistant spawns
add: random trash in bins
add: bookcases in dorms
/:cl:

### CODE REVIEW

**Comment by JohnTheAutist** [comment]
It's gunna conflict with https://github.com/not-a-furry/vmstation/pull/77

Maybe this will help https://tgstation13.org/wiki/Map_Merger If not worst case scenario just update with the latest when that PR gets merged and readd the stuff you added.

**Comment by hamurlik** [comment]
Tool Storage
Forgot to add an image.

**Comment by sperky7933** [comment]
@JohnTheAutist what do you think about this

**Comment by JohnTheAutist** [comment]
> @JohnTheAutist what do you think about this

I think it's fine. He's gunna have to download the latest and readd his changes, though.

**Comment by hamurlik** [comment]
#86 New pull request, with the new version.

**Pull request closed without merging**
