### PR TITLE
Added space merchant ghost spawner

### PR DESCRIPTION
**Pull request by JohnTheAutist**
Space Merchant Ghostspawner

## About The Pull Request

Space merchant ghost spawner. You basically are a squidperson in space with a freighter ship that isn't destroyed. You can fly it around too. 

## Why It's Good For The Game

More spawners. It's fun.

## Changelog
:cl: sneed
add: merchant freighter
add: merchant ghost spawner
/:cl:

### CODE REVIEW

**Comment by sperky7933** [comment]
testing

**Comment by sperky7933** [comment]
1. put a space between . and M 
image
2. fix the atmosphere (bathroom has no air, air alarms are blaring)
3. put solid plasma on the engine, a default twenty stack is suffice 
4. replace the GPS "distress signal" with "merchant barge" or some shit, idk, up to you
5. give them unlocked mining lockers to dabble with mining asteroids

**Comment by JohnTheAutist** [comment]
@not-a-furry 
Fixed all those issues. The plasma is in the box near the SMES. I removed the GPS because people will just jack the freighter before anyone can even use the spawners. Especially if telescience gets added.

**Comment by JohnTheAutist** [comment]
I kinda disagree with giving them mining gear a little bit but I'll just leave it in for now and maybe change it out if I build this out more.

**Pull request merged**
