### PR TITLE
Paperplate branch

### PR DESCRIPTION
**Pull request by ghost**
## Changelog
:cl:
add: Added in a new, craftable shotgun. Breaks after one use but is easier to make than the other improvised shotgun
/:cl:

### CODE REVIEW

**Comment by squidlover** [comment]
tell you what bud. you take back your downvote on my simpsons pr. and i upvote this pr.

**Comment by sperky7933** [comment]
Voted yes in polls, merging & testing tomorrow if i got time

**Comment by sperky7933** [comment]
doesnt display in the crafting menu. fix it and i add it

**Comment by ghost** [comment]
> doesnt display in the crafting menu. fix it and i add it

shotgunpistol_craft
It works fine on my end. Did you remember to do a fresh build?

**Comment by JohnTheAutist** [comment]
> > doesnt display in the crafting menu. fix it and i add it
> 
> shotgunpistol_craft It works fine on my end. Did you remember to do a fresh build?

Maybe create a new PR with that screenshot so the host sees it.

**Pull request closed without merging**
