### PR TITLE
Ministation

### PR DESCRIPTION
**Pull request by JohnTheAutist**
ministation-1

## About The Pull Request

Adds the 2020 version of ministation from hippie. Might be a little rough around the edges and missing some things. It's worth playtesting just to see if people like it.

## Why It's Good For The Game

Lots of complaints about the server map being too big

related https://github.com/not-a-furry/vmstation/issues/12

## Changelog
:cl: sneed
add: Ministation
/:cl:

### CODE REVIEW

**Comment by sperky7933** [comment]
ok i test this out tonight

**Comment by sperky7933** [comment]
issues i see:
1. add maxplayers to ministation, 25 should be suffice
2. move techfab from custodial closet to somewhere else
3. add ticker to HoP line for consistency
4. add janitoral vending machine to custodial closet
5. remove the sleeper, replace with two statis beds
6. fix atmospherics to be consistent with other maps, this also means replacing a row of plasma tanks with N2 tanks
7. add fire axe to atmospherics
8. cargo tech clothing vending machine
9. security clothing vending machine
10. cryo freezer should start off being turned off
11. xenobiology gets only two grey slimes
12. remove law book from cells as retards will use it to break shit

**Comment by JohnTheAutist** [comment]
> fix atmospherics to be consistent with other maps, this also means replacing a row of plasma tanks with N2 tanks

I can fix all those except this. There isn't room for the whole atmos setup copy pasted in and it kinda hurts the theme of the station. I can probably squeeze in a mini gas-mixer chamber, add a freezer/heater and _maybe_ a mini-air mixer chamber. I assumed there would be a compressed down version of atmos since it is a 'Mini' version of the station. The miners aren't capped like on /tg/ station so the recycling waste part isn't necessary. Most atmos techs unwrench and destroy the default mixpipes and it's easier to just create the pipes you want with an RPD.

**Comment by sperky7933** [comment]
> > fix atmospherics to be consistent with other maps, this also means replacing a row of plasma tanks with N2 tanks
> 
> I can fix all those except this. There isn't room for the whole atmos setup copy pasted in and it kinda hurts the theme of the station. I can probably squeeze in a mini gas-mixer chamber, add a freezer/heater and _maybe_ a mini-air mixer chamber. I assumed there would be a compressed down version of atmos since it is a 'Mini' version of the station. The miners aren't capped like on /tg/ station so the recycling waste part isn't necessary. Most atmos techs unwrench and destroy the default mixpipes and it's easier to just create the pipes you want with an RPD.

yeah i don't mean fix the entirety of atmospherics, just make it so there aren't random pipes on the floor, there are pressure pumps to each outlet, you know what i mean.

**Comment by JohnTheAutist** [comment]
> yeah i don't mean fix the entirety of atmospherics, just make it so there aren't random pipes on the floor, there are pressure pumps to each outlet, you know what i mean.
>

I replaced those with layer adapters because there's no room to work in the space atmos provides without them. I was also planning on adding a layer adapter to the mini gas-mixer. The air mix pipe cuts under the floor. I don't really know how to make an obvious transition saying "It's going under the floor now". In regular atmos it just runs into a wall and then goes under the floor on the other side. I do believe I have seen a spot where the floor-tile is removed and then it goes under to signal it's going under the floor

**Comment by sperky7933** [comment]
k

**Comment by JohnTheAutist** [comment]
@not-a-furry 
Changes are in.
ministation-1

**Comment by sperky7933** [comment]
i think i will merge it today and let people bitch about it tonight so we can see what needs changes. you ok with that?

**Comment by JohnTheAutist** [comment]
> i think i will merge it today and let people bitch about it tonight so we can see what needs changes. you ok with that?

Yeah sure. Just let me tweak some things. I keep spotting random things. Right now I noticed the transit pod to AI sat doesn't work.

**Comment by JohnTheAutist** [comment]
@not-a-furry  should be good

**Comment by sperky7933** [comment]
public nanite chamber is a early-mid game science thing that they build themselves. also the freezer & heater should start turned off in atmos. after those two things ill merge

also dog bed for ian

**Comment by sperky7933** [comment]
i would also like to say your adition of an AI cyborg shell is smart, considering this is lowpop map and people r gonna be bored to shit playing ai

**Comment by JohnTheAutist** [comment]
> public nanite chamber is a early-mid game science thing that they build themselves. also the freezer & heater should start turned off in atmos. after those two things ill merge
> 
> also dog bed for ian

done

> i would also like to say your adition of an AI cyborg shell is smart, considering this is lowpop map and people r gonna be bored to shit playing ai

That was in the station already

**Pull request merged**
